# Generated by Django 2.2.7 on 2019-11-19 18:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=15)),
                ('by', models.CharField(max_length=50)),
                ('time', models.IntegerField(default=0)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.IntegerField(default=0, validators=[django.core.validators.int_list_validator])),
                ('parent', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SaltyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salty_score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sarcasm_core', models.DecimalField(decimal_places=3, max_digits=8)),
                ('catagory', models.CharField(default='', max_length=15)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Items')),
            ],
        ),
    ]
