# Generated by Django 2.2.7 on 2019-11-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=15)),
                ('by', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
