# Generated by Django 2.2.7 on 2019-11-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='time',
            field=models.TimeField(),
        ),
    ]
