# Generated by Django 2.2.7 on 2019-11-19 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='kids',
            field=models.CharField(max_length=300, validators=[django.core.validators.int_list_validator]),
        ),
    ]
