# Generated by Django 2.2.7 on 2019-11-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191119_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saltyuser',
            name='by',
            field=models.CharField(max_length=50),
        ),
    ]
