# Generated by Django 2.2.7 on 2019-11-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191118_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='time',
            field=models.IntegerField(),
        ),
    ]
