# Generated by Django 2.2.7 on 2019-11-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191118_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='parent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
