# Generated by Django 2.2.7 on 2019-11-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191120_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='dead',
        ),
        migrations.RemoveField(
            model_name='items',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='items',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='items',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='items',
            name='time',
        ),
    ]
