# Generated by Django 2.2.7 on 2019-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191120_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saltyuser',
            old_name='catagory',
            new_name='rank',
        ),
        migrations.RemoveField(
            model_name='saltyuser',
            name='sarcasm_core',
        ),
        migrations.AlterField(
            model_name='saltyuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
