# Generated by Django 2.2.7 on 2019-11-19 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191119_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='kids',
            field=models.IntegerField(default=0, validators=[django.core.validators.int_list_validator]),
        ),
    ]
