# Generated by Django 2.2.7 on 2019-11-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_items_kids'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaltyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('catagory', models.CharField(default='', max_length=15)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Items')),
            ],
        ),
    ]
