# Generated by Django 2.2.7 on 2019-11-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191120_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saltyuser',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='saltyuser',
            old_name='salty_score',
            new_name='comment_saltiness_score',
        ),
        migrations.RenameField(
            model_name='saltyuser',
            old_name='by',
            new_name='hacker',
        ),
        migrations.RenameField(
            model_name='saltyuser',
            old_name='rank',
            new_name='hacker_salt_ranking',
        ),
    ]
