# Generated by Django 2.2.7 on 2019-11-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191120_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='saltyuser',
            options={'ordering': ('hacker_salt_ranking',)},
        ),
    ]
